### ISSUE TITLE
Prueba Unitaria1

### ISSUE THREAD

**Issue by USERcndv2021** [USERcndv2021/DAW_PRUEBAS_UNITARIAS_2223#1]
Hola @jrgs,

Por favor, ¿podrías echarle un vistazo a los métodos de prueba realizados y señalarme los posibles errores?

En principio todas las pruebas han sido superadas, pero tengo una duda con respecto a los valores fronteras del método **realizarIngreso** y no sé si lo estoy haciendo bien. La duda es ¿sería correcto que el límite (por arriba) de un ingreso sea el valor máximo que se pueda introducir en la variable definida para tal efecto?

Gracias.
Claudia Dielma.

**Comment by jrgs** [comment]
Hola @USERcndv2021,
Has hecho un montón de métodos de prueba ;) Para empezar, los de excepciones, muy bien, así tienen que ser. Ahí puedes probar límites como saldo=0 o saldo=-1.
También puedes 'reciclar' métodos, usando varios Assert:

```
            double saldoInicial = 500;
            double reintegro = 250;
            double saldoEsperado = 250;
            GestionBancariaApp miApp = new GestionBancariaApp(saldoInicial);
            // Método a probar
            miApp.realizarReintegro(reintegro);
            Assert.AreEqual(saldoEsperado, miApp.obtenerSaldo(), 0.001, "Se produjo un error al realizar el reintegro, saldo" +
            "incorrecto.");

           saldoEsperado -= reintegro;
            miApp.realizarReintegro(reintegro);
            Assert.AreEqual(saldoEsperado, miApp.obtenerSaldo(), 0.001,  "Se produjo un error al realizar el reintegro, saldo" +
            "incorrecto.");
```
Luego hay algún método donde el mensaje del Assert no es correcto y no has puesto el margen de cálculo:
` Assert.AreEqual(saldoEsperado, actual, "El balance de la cuenta es correcto");`
